name: CI

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches: ["*"]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Check lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          args: --timeout 5m  --config .golangci.yml
